# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(908, 471)
        self.hishorytable = QtWidgets.QTableWidget(History)
        self.hishorytable.setGeometry(QtCore.QRect(20, 90, 867, 361))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.hishorytable.setFont(font)
        self.hishorytable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.hishorytable.setStyleSheet("QTableWidget{\n"
"    border: 2px solid #fe0000;\n"
"    selection-background-color: #ff9966;\n"
"}\n"
"QTableWidget::item::hover{\n"
"    background-color: #ffcc66;\n"
"}\n"
"QTableWidget QHeaderView::section{\n"
"    background-color: #F0F0F0;\n"
"    border: none\n"
"}\n"
"QTableWidget QHeaderView::section::hover{\n"
"    background-color: #ffcc66;\n"
"    border: none;\n"
"}\n"
"QTableWidget::item#3{\n"
"    background-color:#bfa\n"
"}\n"
"")
        self.hishorytable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hishorytable.setLineWidth(1)
        self.hishorytable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.hishorytable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.hishorytable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.hishorytable.setAutoScrollMargin(16)
        self.hishorytable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.hishorytable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.hishorytable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.hishorytable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.hishorytable.setShowGrid(True)
        self.hishorytable.setGridStyle(QtCore.Qt.SolidLine)
        self.hishorytable.setWordWrap(True)
        self.hishorytable.setCornerButtonEnabled(True)
        self.hishorytable.setRowCount(1)
        self.hishorytable.setColumnCount(7)
        self.hishorytable.setObjectName("hishorytable")
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hishorytable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hishorytable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hishorytable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hishorytable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hishorytable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hishorytable.setItem(0, 4, item)
        self.hishorytable.horizontalHeader().setVisible(True)
        self.hishorytable.horizontalHeader().setCascadingSectionResizes(False)
        self.hishorytable.horizontalHeader().setDefaultSectionSize(126)
        self.hishorytable.horizontalHeader().setHighlightSections(True)
        self.hishorytable.horizontalHeader().setMinimumSectionSize(40)
        self.hishorytable.horizontalHeader().setSortIndicatorShown(True)
        self.hishorytable.horizontalHeader().setStretchLastSection(True)
        self.hishorytable.verticalHeader().setVisible(False)
        self.hishorytable.verticalHeader().setCascadingSectionResizes(False)
        self.hishorytable.verticalHeader().setDefaultSectionSize(52)
        self.hishorytable.verticalHeader().setMinimumSectionSize(30)
        self.hishorytable.verticalHeader().setSortIndicatorShown(False)
        self.hishorytable.verticalHeader().setStretchLastSection(False)
        self.history_label = QtWidgets.QLabel(History)
        self.history_label.setGeometry(QtCore.QRect(305, 20, 296, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.history_label.setFont(font)
        self.history_label.setObjectName("history_label")

        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "历史记录"))
        self.hishorytable.setSortingEnabled(True)
        item = self.hishorytable.verticalHeaderItem(0)
        item.setText(_translate("History", "新建行"))
        item = self.hishorytable.horizontalHeaderItem(0)
        item.setText(_translate("History", "视频路径"))
        item = self.hishorytable.horizontalHeaderItem(1)
        item.setText(_translate("History", "视频id"))
        item = self.hishorytable.horizontalHeaderItem(2)
        item.setText(_translate("History", "视频时长"))
        item = self.hishorytable.horizontalHeaderItem(3)
        item.setText(_translate("History", "视频置信度"))
        item = self.hishorytable.horizontalHeaderItem(4)
        item.setText(_translate("History", "日期"))
        __sortingEnabled = self.hishorytable.isSortingEnabled()
        self.hishorytable.setSortingEnabled(False)
        item = self.hishorytable.item(0, 1)
        item.setText(_translate("History", "1"))
        item = self.hishorytable.item(0, 2)
        item.setText(_translate("History", "3"))
        item = self.hishorytable.item(0, 3)
        item.setText(_translate("History", "4"))
        item = self.hishorytable.item(0, 4)
        item.setText(_translate("History", "2"))
        self.hishorytable.setSortingEnabled(__sortingEnabled)
        self.history_label.setText(_translate("History", "识别视频历史记录"))
