# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TOTAL(object):
    def setupUi(self, TOTAL):
        TOTAL.setObjectName("TOTAL")
        TOTAL.resize(1600, 915)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TOTAL.sizePolicy().hasHeightForWidth())
        TOTAL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        TOTAL.setFont(font)
        TOTAL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(TOTAL)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(15, 20, 1570, 875))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("QTabWidget QWidget#about{\n"
"    background-color:#f0f0f0\n"
"}\n"
"QTabWidget QWidget#ReID{\n"
"    background-color:#f0f0f0\n"
"}\n"
"QTabBar::tab{\n"
"background:#FFAA50;color:white;\n"
"padding: 7px 45px;\n"
"margin-left: 50px;\n"
"margin-top: 18px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"background:rgb(255,255,255,100);\n"
"}\n"
"QTabBar::tab:selected{\n"
"border-color:white;background:white;color:#FC5531;\n"
"}\n"
"QTabBar{\n"
"background-color:#FFAA50;\n"
"margin-left: -25px;\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pic_module = QtWidgets.QWidget()
        self.pic_module.setObjectName("pic_module")
        self.pic = QtWidgets.QPushButton(self.pic_module)
        self.pic.setGeometry(QtCore.QRect(461, 226, 281, 271))
        self.pic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pic.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.pic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/picture2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic.setIcon(icon)
        self.pic.setIconSize(QtCore.QSize(300, 300))
        self.pic.setObjectName("pic")
        self.save = QtWidgets.QPushButton(self.pic_module)
        self.save.setGeometry(QtCore.QRect(1425, 751, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:1px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:21px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:20px;\n"
"                    color:white;}\n"
"")
        self.save.setIconSize(QtCore.QSize(80, 80))
        self.save.setObjectName("save")
        self.pushButton = QtWidgets.QPushButton(self.pic_module)
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../images/rigthangle_tl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../images/rightangle_bl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_3.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../images/rightangle_tr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_4.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../images/rightangle_br.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.pic_module)
        self.label_2.setGeometry(QtCore.QRect(1332, 24, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_12 = QtWidgets.QFrame(self.pic_module)
        self.line_12.setGeometry(QtCore.QRect(1281, 61, 252, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.reselect_img = QtWidgets.QPushButton(self.pic_module)
        self.reselect_img.setGeometry(QtCore.QRect(850, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reselect_img.setFont(font)
        self.reselect_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reselect_img.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reselect_img.setIconSize(QtCore.QSize(80, 80))
        self.reselect_img.setObjectName("reselect_img")
        self.picture_8 = QtWidgets.QPushButton(self.pic_module)
        self.picture_8.setGeometry(QtCore.QRect(1290, 85, 69, 65))
        self.picture_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_8.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../images/count.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_8.setIcon(icon5)
        self.picture_8.setIconSize(QtCore.QSize(55, 55))
        self.picture_8.setObjectName("picture_8")
        self.count_img = QtWidgets.QLabel(self.pic_module)
        self.count_img.setGeometry(QtCore.QRect(1364, 102, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_img.setFont(font)
        self.count_img.setObjectName("count_img")
        self.picture_9 = QtWidgets.QPushButton(self.pic_module)
        self.picture_9.setGeometry(QtCore.QRect(1298, 184, 54, 50))
        self.picture_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_9.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_9.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../images/confidence_coefficient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_9.setIcon(icon6)
        self.picture_9.setIconSize(QtCore.QSize(50, 50))
        self.picture_9.setObjectName("picture_9")
        self.confidence_coefficient_img = QtWidgets.QLabel(self.pic_module)
        self.confidence_coefficient_img.setGeometry(QtCore.QRect(1370, 192, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_img.setFont(font)
        self.confidence_coefficient_img.setObjectName("confidence_coefficient_img")
        self.Slider = QtWidgets.QSlider(self.pic_module)
        self.Slider.setGeometry(QtCore.QRect(1303, 342, 211, 22))
        self.Slider.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider.setMinimum(1)
        self.Slider.setMaximum(100)
        self.Slider.setSingleStep(1)
        self.Slider.setPageStep(1)
        self.Slider.setProperty("value", 50)
        self.Slider.setSliderPosition(50)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.threshold_img = QtWidgets.QLabel(self.pic_module)
        self.threshold_img.setGeometry(QtCore.QRect(1364, 282, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_img.setFont(font)
        self.threshold_img.setObjectName("threshold_img")
        self.picture_10 = QtWidgets.QPushButton(self.pic_module)
        self.picture_10.setGeometry(QtCore.QRect(1300, 272, 54, 50))
        self.picture_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_10.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_10.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../images/threshold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_10.setIcon(icon7)
        self.picture_10.setIconSize(QtCore.QSize(53, 53))
        self.picture_10.setObjectName("picture_10")
        self.represent_img = QtWidgets.QLabel(self.pic_module)
        self.represent_img.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_img.setStyleSheet("QLabel{\n"
"background-color:\n"
"}")
        self.represent_img.setText("")
        self.represent_img.setObjectName("represent_img")
        self.label = QtWidgets.QLabel(self.pic_module)
        self.label.setGeometry(QtCore.QRect(1304, 361, 8, 15))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.pic_module)
        self.label_6.setGeometry(QtCore.QRect(1510, 361, 8, 15))
        self.label_6.setObjectName("label_6")
        self.submit_img = QtWidgets.QPushButton(self.pic_module)
        self.submit_img.setGeometry(QtCore.QRect(220, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submit_img.setFont(font)
        self.submit_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_img.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.submit_img.setIconSize(QtCore.QSize(80, 80))
        self.submit_img.setObjectName("submit_img")
        self.picture = QtWidgets.QPushButton(self.pic_module)
        self.picture.setGeometry(QtCore.QRect(530, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.picture.setFont(font)
        self.picture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.picture.setIconSize(QtCore.QSize(80, 80))
        self.picture.setObjectName("picture")
        self.img_list = QtWidgets.QListWidget(self.pic_module)
        self.img_list.setGeometry(QtCore.QRect(1289, 478, 238, 261))
        self.img_list.setObjectName("img_list")
        self.line_14 = QtWidgets.QFrame(self.pic_module)
        self.line_14.setGeometry(QtCore.QRect(1282, 400, 252, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_8 = QtWidgets.QLabel(self.pic_module)
        self.label_8.setGeometry(QtCore.QRect(1333, 427, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.pic_module)
        self.label_9.setGeometry(QtCore.QRect(1281, 12, 251, 781))
        self.label_9.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.allchecked = QtWidgets.QPushButton(self.pic_module)
        self.allchecked.setGeometry(QtCore.QRect(1289, 751, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allchecked.setFont(font)
        self.allchecked.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allchecked.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:1px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:21px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:20px;\n"
"                    color:white;}\n"
"")
        self.allchecked.setIconSize(QtCore.QSize(80, 80))
        self.allchecked.setObjectName("allchecked")
        self.allunchecked = QtWidgets.QPushButton(self.pic_module)
        self.allunchecked.setGeometry(QtCore.QRect(1289, 751, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allunchecked.setFont(font)
        self.allunchecked.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allunchecked.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:1px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:21px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:20px;\n"
"                    color:white;}\n"
"")
        self.allunchecked.setIconSize(QtCore.QSize(80, 80))
        self.allunchecked.setObjectName("allunchecked")
        self.waiting = QtWidgets.QLabel(self.pic_module)
        self.waiting.setGeometry(QtCore.QRect(401, 336, 451, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.waiting.setFont(font)
        self.waiting.setObjectName("waiting")
        self.represent_img.raise_()
        self.waiting.raise_()
        self.pic.raise_()
        self.label_9.raise_()
        self.save.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_2.raise_()
        self.line_12.raise_()
        self.reselect_img.raise_()
        self.picture_8.raise_()
        self.count_img.raise_()
        self.picture_9.raise_()
        self.confidence_coefficient_img.raise_()
        self.Slider.raise_()
        self.threshold_img.raise_()
        self.picture_10.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.submit_img.raise_()
        self.picture.raise_()
        self.img_list.raise_()
        self.line_14.raise_()
        self.label_8.raise_()
        self.allchecked.raise_()
        self.allunchecked.raise_()
        self.tabWidget.addTab(self.pic_module, "")
        self.vdo_module = QtWidgets.QWidget()
        self.vdo_module.setObjectName("vdo_module")
        self.confidence_coefficient_vdo = QtWidgets.QLabel(self.vdo_module)
        self.confidence_coefficient_vdo.setGeometry(QtCore.QRect(1370, 192, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_vdo.setFont(font)
        self.confidence_coefficient_vdo.setObjectName("confidence_coefficient_vdo")
        self.pushButton_9 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.picture_11 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_11.setGeometry(QtCore.QRect(1290, 85, 69, 65))
        self.picture_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_11.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_11.setText("")
        self.picture_11.setIcon(icon5)
        self.picture_11.setIconSize(QtCore.QSize(55, 55))
        self.picture_11.setObjectName("picture_11")
        self.picture_12 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_12.setGeometry(QtCore.QRect(1300, 272, 54, 50))
        self.picture_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_12.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_12.setText("")
        self.picture_12.setIcon(icon7)
        self.picture_12.setIconSize(QtCore.QSize(53, 53))
        self.picture_12.setObjectName("picture_12")
        self.label_4 = QtWidgets.QLabel(self.vdo_module)
        self.label_4.setGeometry(QtCore.QRect(1281, 12, 251, 781))
        self.label_4.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.submit_vdo = QtWidgets.QPushButton(self.vdo_module)
        self.submit_vdo.setGeometry(QtCore.QRect(220, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submit_vdo.setFont(font)
        self.submit_vdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_vdo.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.submit_vdo.setIconSize(QtCore.QSize(80, 80))
        self.submit_vdo.setObjectName("submit_vdo")
        self.line_13 = QtWidgets.QFrame(self.vdo_module)
        self.line_13.setGeometry(QtCore.QRect(1281, 61, 252, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_11.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.picture_13 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_13.setGeometry(QtCore.QRect(1298, 184, 54, 50))
        self.picture_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_13.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_13.setText("")
        self.picture_13.setIcon(icon6)
        self.picture_13.setIconSize(QtCore.QSize(50, 50))
        self.picture_13.setObjectName("picture_13")
        self.threshold_vdo = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo.setGeometry(QtCore.QRect(1364, 282, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_vdo.setFont(font)
        self.threshold_vdo.setObjectName("threshold_vdo")
        self.pushButton_15 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_15.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon3)
        self.pushButton_15.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_16.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon2)
        self.pushButton_16.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.vdo = QtWidgets.QPushButton(self.vdo_module)
        self.vdo.setGeometry(QtCore.QRect(461, 226, 304, 300))
        self.vdo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.vdo.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.vdo.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../images/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vdo.setIcon(icon8)
        self.vdo.setIconSize(QtCore.QSize(300, 300))
        self.vdo.setObjectName("vdo")
        self.represent_vdo = QtWidgets.QLabel(self.vdo_module)
        self.represent_vdo.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_vdo.setStyleSheet("QLabel{\n"
"background-color: \n"
"}")
        self.represent_vdo.setText("")
        self.represent_vdo.setObjectName("represent_vdo")
        self.reselect_vdo = QtWidgets.QPushButton(self.vdo_module)
        self.reselect_vdo.setGeometry(QtCore.QRect(950, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reselect_vdo.setFont(font)
        self.reselect_vdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reselect_vdo.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reselect_vdo.setIconSize(QtCore.QSize(80, 80))
        self.reselect_vdo.setObjectName("reselect_vdo")
        self.video = QtWidgets.QPushButton(self.vdo_module)
        self.video.setGeometry(QtCore.QRect(530, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.video.setFont(font)
        self.video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.video.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.video.setIconSize(QtCore.QSize(80, 80))
        self.video.setObjectName("video")
        self.Slider_2 = QtWidgets.QSlider(self.vdo_module)
        self.Slider_2.setGeometry(QtCore.QRect(1303, 342, 211, 22))
        self.Slider_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider_2.setMinimum(1)
        self.Slider_2.setMaximum(100)
        self.Slider_2.setSingleStep(1)
        self.Slider_2.setPageStep(1)
        self.Slider_2.setProperty("value", 90)
        self.Slider_2.setSliderPosition(90)
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setObjectName("Slider_2")
        self.label_3 = QtWidgets.QLabel(self.vdo_module)
        self.label_3.setGeometry(QtCore.QRect(1304, 361, 8, 15))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.vdo_module)
        self.label_7.setGeometry(QtCore.QRect(1510, 361, 8, 15))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.vdo_module)
        self.label_5.setGeometry(QtCore.QRect(1332, 24, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.picture_17 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_17.setGeometry(QtCore.QRect(1300, 491, 54, 50))
        self.picture_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_17.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_17.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../images/pisition.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_17.setIcon(icon9)
        self.picture_17.setIconSize(QtCore.QSize(50, 50))
        self.picture_17.setObjectName("picture_17")
        self.threshold_vdo_2 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_2.setGeometry(QtCore.QRect(1364, 501, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_vdo_2.setFont(font)
        self.threshold_vdo_2.setObjectName("threshold_vdo_2")
        self.line_17 = QtWidgets.QFrame(self.vdo_module)
        self.line_17.setGeometry(QtCore.QRect(1282, 413, 252, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.idBox = QtWidgets.QComboBox(self.vdo_module)
        self.idBox.setGeometry(QtCore.QRect(1412, 442, 111, 26))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idBox.setFont(font)
        self.idBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.idBox.setStyleSheet("QComboBox{\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #000;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    border-image: url(E:/python/Competition/PYQT/images/drop.png)\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: none;\n"
"}")
        self.idBox.setObjectName("idBox")
        self.idBox.addItem("")
        self.idBox.setItemText(0, "")
        self.threshold_vdo_3 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_3.setGeometry(QtCore.QRect(1295, 570, 59, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.threshold_vdo_3.setFont(font)
        self.threshold_vdo_3.setObjectName("threshold_vdo_3")
        self.threshold_vdo_4 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_4.setGeometry(QtCore.QRect(1419, 631, 53, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.threshold_vdo_4.setFont(font)
        self.threshold_vdo_4.setObjectName("threshold_vdo_4")
        self.threshold_vdo_5 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_5.setGeometry(QtCore.QRect(1295, 631, 59, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.threshold_vdo_5.setFont(font)
        self.threshold_vdo_5.setObjectName("threshold_vdo_5")
        self.threshold_vdo_6 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_6.setGeometry(QtCore.QRect(1419, 570, 53, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.threshold_vdo_6.setFont(font)
        self.threshold_vdo_6.setObjectName("threshold_vdo_6")
        self.id = QtWidgets.QLabel(self.vdo_module)
        self.id.setGeometry(QtCore.QRect(1290, 436, 136, 33))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.xmax = QtWidgets.QLabel(self.vdo_module)
        self.xmax.setGeometry(QtCore.QRect(1355, 570, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.xmax.setFont(font)
        self.xmax.setObjectName("xmax")
        self.xmin = QtWidgets.QLabel(self.vdo_module)
        self.xmin.setGeometry(QtCore.QRect(1472, 570, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.xmin.setFont(font)
        self.xmin.setObjectName("xmin")
        self.ymin = QtWidgets.QLabel(self.vdo_module)
        self.ymin.setGeometry(QtCore.QRect(1472, 631, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ymin.setFont(font)
        self.ymin.setObjectName("ymin")
        self.ymax = QtWidgets.QLabel(self.vdo_module)
        self.ymax.setGeometry(QtCore.QRect(1355, 631, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ymax.setFont(font)
        self.ymax.setObjectName("ymax")
        self.line_18 = QtWidgets.QFrame(self.vdo_module)
        self.line_18.setGeometry(QtCore.QRect(1281, 671, 252, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.person_counting = QtWidgets.QPushButton(self.vdo_module)
        self.person_counting.setGeometry(QtCore.QRect(1329, 717, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.person_counting.setFont(font)
        self.person_counting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.person_counting.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.person_counting.setIconSize(QtCore.QSize(80, 80))
        self.person_counting.setObjectName("person_counting")
        self.ROI_btn = QtWidgets.QPushButton(self.vdo_module)
        self.ROI_btn.setGeometry(QtCore.QRect(1329, 717, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ROI_btn.setFont(font)
        self.ROI_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ROI_btn.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.ROI_btn.setIconSize(QtCore.QSize(80, 80))
        self.ROI_btn.setObjectName("ROI_btn")
        self.viewcount_vdo_total = QtWidgets.QLabel(self.vdo_module)
        self.viewcount_vdo_total.setGeometry(QtCore.QRect(1360, 93, 112, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.viewcount_vdo_total.setFont(font)
        self.viewcount_vdo_total.setObjectName("viewcount_vdo_total")
        self.viewcount_vdo_ROI = QtWidgets.QLabel(self.vdo_module)
        self.viewcount_vdo_ROI.setGeometry(QtCore.QRect(1365, 130, 112, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.viewcount_vdo_ROI.setFont(font)
        self.viewcount_vdo_ROI.setObjectName("viewcount_vdo_ROI")
        self.count_vdo = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo.setGeometry(QtCore.QRect(1364, 102, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_vdo.setFont(font)
        self.count_vdo.setObjectName("count_vdo")
        self.count_vdo_total = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo_total.setGeometry(QtCore.QRect(1481, 94, 48, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_vdo_total.setFont(font)
        self.count_vdo_total.setObjectName("count_vdo_total")
        self.count_vdo_ROI = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo_ROI.setGeometry(QtCore.QRect(1478, 133, 48, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_vdo_ROI.setFont(font)
        self.count_vdo_ROI.setObjectName("count_vdo_ROI")
        self.label_12 = QtWidgets.QLabel(self.vdo_module)
        self.label_12.setGeometry(QtCore.QRect(1468, 90, 14, 28))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(17)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progressBar = QtWidgets.QProgressBar(self.vdo_module)
        self.progressBar.setGeometry(QtCore.QRect(121, 720, 821, 41))
        self.progressBar.setStyleSheet("QProgressBar::chunk{\n"
"    border: 2px solid #FE3C46/*边框以及边框颜色*/;\n"
"    border-radius: 5px;\n"
"    background-color: #FE3C46;\n"
"    margin:  0 0.5px;\n"
"    width: 10px;\n"
"}\n"
"QProgressBar{\n"
"    border: 2px solid #FE3C46;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    font-size: 25px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_16 = QtWidgets.QLabel(self.vdo_module)
        self.label_16.setGeometry(QtCore.QRect(470, 770, 124, 34))
        font = QtGui.QFont()
        font.setFamily("Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.history = QtWidgets.QPushButton(self.vdo_module)
        self.history.setGeometry(QtCore.QRect(1329, 717, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.history.setFont(font)
        self.history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.history.setIconSize(QtCore.QSize(80, 80))
        self.history.setObjectName("history")
        self.progressBar.raise_()
        self.vdo.raise_()
        self.represent_vdo.raise_()
        self.label_4.raise_()
        self.confidence_coefficient_vdo.raise_()
        self.pushButton_9.raise_()
        self.picture_11.raise_()
        self.picture_12.raise_()
        self.submit_vdo.raise_()
        self.line_13.raise_()
        self.pushButton_11.raise_()
        self.picture_13.raise_()
        self.threshold_vdo.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.reselect_vdo.raise_()
        self.video.raise_()
        self.Slider_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.picture_17.raise_()
        self.threshold_vdo_2.raise_()
        self.line_17.raise_()
        self.idBox.raise_()
        self.threshold_vdo_3.raise_()
        self.threshold_vdo_4.raise_()
        self.threshold_vdo_5.raise_()
        self.threshold_vdo_6.raise_()
        self.id.raise_()
        self.xmax.raise_()
        self.xmin.raise_()
        self.ymin.raise_()
        self.ymax.raise_()
        self.line_18.raise_()
        self.person_counting.raise_()
        self.ROI_btn.raise_()
        self.viewcount_vdo_total.raise_()
        self.viewcount_vdo_ROI.raise_()
        self.count_vdo_total.raise_()
        self.count_vdo_ROI.raise_()
        self.label_12.raise_()
        self.count_vdo.raise_()
        self.label_16.raise_()
        self.history.raise_()
        self.tabWidget.addTab(self.vdo_module, "")
        self.cam_module = QtWidgets.QWidget()
        self.cam_module.setObjectName("cam_module")
        self.line_15 = QtWidgets.QFrame(self.cam_module)
        self.line_15.setGeometry(QtCore.QRect(1281, 72, 252, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.picture_14 = QtWidgets.QPushButton(self.cam_module)
        self.picture_14.setGeometry(QtCore.QRect(1290, 96, 69, 65))
        self.picture_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_14.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_14.setText("")
        self.picture_14.setIcon(icon5)
        self.picture_14.setIconSize(QtCore.QSize(55, 55))
        self.picture_14.setObjectName("picture_14")
        self.allchecked_2 = QtWidgets.QPushButton(self.cam_module)
        self.allchecked_2.setGeometry(QtCore.QRect(1289, 762, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allchecked_2.setFont(font)
        self.allchecked_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allchecked_2.setStyleSheet("QPushButton{background-color:rgb(254,0,0);\n"
"                    border:2px solid #fe0000;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:18px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:17px;\n"
"                    color:white;}\n"
"")
        self.allchecked_2.setIconSize(QtCore.QSize(80, 80))
        self.allchecked_2.setObjectName("allchecked_2")
        self.pic_2 = QtWidgets.QPushButton(self.cam_module)
        self.pic_2.setGeometry(QtCore.QRect(462, 230, 279, 275))
        self.pic_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pic_2.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.pic_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../images/camere.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic_2.setIcon(icon10)
        self.pic_2.setIconSize(QtCore.QSize(275, 275))
        self.pic_2.setObjectName("pic_2")
        self.picture_15 = QtWidgets.QPushButton(self.cam_module)
        self.picture_15.setGeometry(QtCore.QRect(1300, 283, 54, 50))
        self.picture_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_15.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_15.setText("")
        self.picture_15.setIcon(icon7)
        self.picture_15.setIconSize(QtCore.QSize(53, 53))
        self.picture_15.setObjectName("picture_15")
        self.picture_16 = QtWidgets.QPushButton(self.cam_module)
        self.picture_16.setGeometry(QtCore.QRect(1298, 195, 54, 50))
        self.picture_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_16.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_16.setText("")
        self.picture_16.setIcon(icon6)
        self.picture_16.setIconSize(QtCore.QSize(50, 50))
        self.picture_16.setObjectName("picture_16")
        self.save_2 = QtWidgets.QPushButton(self.cam_module)
        self.save_2.setGeometry(QtCore.QRect(1425, 762, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_2.setFont(font)
        self.save_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_2.setStyleSheet("QPushButton{background-color:rgb(254,0,0);\n"
"                    border:2px solid #fe0000;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:18px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:17px;\n"
"                    color:white;}\n"
"")
        self.save_2.setIconSize(QtCore.QSize(80, 80))
        self.save_2.setObjectName("save_2")
        self.label_10 = QtWidgets.QLabel(self.cam_module)
        self.label_10.setGeometry(QtCore.QRect(1510, 372, 8, 15))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.cam_module)
        self.label_11.setGeometry(QtCore.QRect(1281, 12, 253, 781))
        self.label_11.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.count_cam = QtWidgets.QLabel(self.cam_module)
        self.count_cam.setGeometry(QtCore.QRect(1364, 102, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_cam.setFont(font)
        self.count_cam.setObjectName("count_cam")
        self.confidence_coefficient_cam = QtWidgets.QLabel(self.cam_module)
        self.confidence_coefficient_cam.setGeometry(QtCore.QRect(1370, 192, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_cam.setFont(font)
        self.confidence_coefficient_cam.setObjectName("confidence_coefficient_cam")
        self.pushButton_5 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_5.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.threshold_cam = QtWidgets.QLabel(self.cam_module)
        self.threshold_cam.setGeometry(QtCore.QRect(1364, 282, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_cam.setFont(font)
        self.threshold_cam.setObjectName("threshold_cam")
        self.label_13 = QtWidgets.QLabel(self.cam_module)
        self.label_13.setGeometry(QtCore.QRect(1304, 361, 8, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.cam_module)
        self.label_14.setGeometry(QtCore.QRect(1332, 24, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Slider_3 = QtWidgets.QSlider(self.cam_module)
        self.Slider_3.setGeometry(QtCore.QRect(1303, 342, 211, 22))
        self.Slider_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider_3.setMinimum(1)
        self.Slider_3.setMaximum(100)
        self.Slider_3.setSingleStep(1)
        self.Slider_3.setPageStep(1)
        self.Slider_3.setProperty("value", 90)
        self.Slider_3.setSliderPosition(90)
        self.Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_3.setObjectName("Slider_3")
        self.represent_cam = QtWidgets.QLabel(self.cam_module)
        self.represent_cam.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_cam.setStyleSheet("QLabel{\n"
"background-color: \n"
"}")
        self.represent_cam.setText("")
        self.represent_cam.setObjectName("represent_cam")
        self.camera = QtWidgets.QPushButton(self.cam_module)
        self.camera.setGeometry(QtCore.QRect(498, 720, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.camera.setIconSize(QtCore.QSize(80, 80))
        self.camera.setObjectName("camera")
        self.line_16 = QtWidgets.QFrame(self.cam_module)
        self.line_16.setGeometry(QtCore.QRect(1281, 411, 252, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.pushButton_7 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_8.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.picture_35 = QtWidgets.QPushButton(self.cam_module)
        self.picture_35.setGeometry(QtCore.QRect(1300, 272, 54, 50))
        self.picture_35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_35.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_35.setText("")
        self.picture_35.setIcon(icon7)
        self.picture_35.setIconSize(QtCore.QSize(53, 53))
        self.picture_35.setObjectName("picture_35")
        self.picture_36 = QtWidgets.QPushButton(self.cam_module)
        self.picture_36.setGeometry(QtCore.QRect(1298, 184, 54, 50))
        self.picture_36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_36.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_36.setText("")
        self.picture_36.setIcon(icon6)
        self.picture_36.setIconSize(QtCore.QSize(50, 50))
        self.picture_36.setObjectName("picture_36")
        self.picture_37 = QtWidgets.QPushButton(self.cam_module)
        self.picture_37.setGeometry(QtCore.QRect(1290, 85, 69, 65))
        self.picture_37.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_37.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_37.setText("")
        self.picture_37.setIcon(icon5)
        self.picture_37.setIconSize(QtCore.QSize(55, 55))
        self.picture_37.setObjectName("picture_37")
        self.label_40 = QtWidgets.QLabel(self.cam_module)
        self.label_40.setGeometry(QtCore.QRect(1510, 361, 8, 15))
        self.label_40.setObjectName("label_40")
        self.camera_off = QtWidgets.QPushButton(self.cam_module)
        self.camera_off.setGeometry(QtCore.QRect(498, 720, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.camera_off.setFont(font)
        self.camera_off.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_off.setStyleSheet("QPushButton{background-color:rgb(254,0,0);\n"
"                    border:2px solid #fe0000;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.camera_off.setIconSize(QtCore.QSize(80, 80))
        self.camera_off.setObjectName("camera_off")
        self.camera_off.raise_()
        self.pic_2.raise_()
        self.represent_cam.raise_()
        self.line_15.raise_()
        self.picture_14.raise_()
        self.allchecked_2.raise_()
        self.picture_15.raise_()
        self.picture_16.raise_()
        self.save_2.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.count_cam.raise_()
        self.confidence_coefficient_cam.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.threshold_cam.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.Slider_3.raise_()
        self.camera.raise_()
        self.line_16.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.picture_35.raise_()
        self.picture_36.raise_()
        self.picture_37.raise_()
        self.label_40.raise_()
        self.tabWidget.addTab(self.cam_module, "")
        self.ReID = QtWidgets.QWidget()
        self.ReID.setObjectName("ReID")
        self.reID_vdo = QtWidgets.QPushButton(self.ReID)
        self.reID_vdo.setGeometry(QtCore.QRect(530, 680, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reID_vdo.setFont(font)
        self.reID_vdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reID_vdo.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reID_vdo.setIconSize(QtCore.QSize(80, 80))
        self.reID_vdo.setObjectName("reID_vdo")
        self.reID_reperson = QtWidgets.QPushButton(self.ReID)
        self.reID_reperson.setGeometry(QtCore.QRect(1325, 750, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reID_reperson.setFont(font)
        self.reID_reperson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reID_reperson.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reID_reperson.setIconSize(QtCore.QSize(80, 80))
        self.reID_reperson.setObjectName("reID_reperson")
        self.reID_submit = QtWidgets.QPushButton(self.ReID)
        self.reID_submit.setGeometry(QtCore.QRect(300, 750, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reID_submit.setFont(font)
        self.reID_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reID_submit.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reID_submit.setIconSize(QtCore.QSize(80, 80))
        self.reID_submit.setObjectName("reID_submit")
        self.reID_progressBar = QtWidgets.QProgressBar(self.ReID)
        self.reID_progressBar.setEnabled(True)
        self.reID_progressBar.setGeometry(QtCore.QRect(200, 190, 821, 41))
        self.reID_progressBar.setMouseTracking(False)
        self.reID_progressBar.setTabletTracking(False)
        self.reID_progressBar.setAcceptDrops(False)
        self.reID_progressBar.setAutoFillBackground(False)
        self.reID_progressBar.setStyleSheet("QProgressBar::chunk{\n"
"    border: 2px solid #FE3C46;  /*边框以及边框颜色*/\n"
"    border-radius: 5px;\n"
"    background-color: #FE3C46;\n"
"}\n"
"QProgressBar{\n"
"    border: 2px solid #FE3C46;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"")
        self.reID_progressBar.setMaximum(0)
        self.reID_progressBar.setProperty("value", 0)
        self.reID_progressBar.setTextVisible(True)
        self.reID_progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.reID_progressBar.setInvertedAppearance(False)
        self.reID_progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.reID_progressBar.setObjectName("reID_progressBar")
        self.vdolist = QtWidgets.QListWidget(self.ReID)
        self.vdolist.setGeometry(QtCore.QRect(10, 370, 1230, 370))
        self.vdolist.setObjectName("vdolist")
        self.reslist = QtWidgets.QListWidget(self.ReID)
        self.reslist.setGeometry(QtCore.QRect(10, 10, 1230, 350))
        self.reslist.setObjectName("reslist")
        self.targetpic = QtWidgets.QLabel(self.ReID)
        self.targetpic.setGeometry(QtCore.QRect(1252, 170, 300, 570))
        self.targetpic.setStyleSheet("QLabel{\n"
"    background-color: #fff;\n"
"    border: 1px solid #000;\n"
"}")
        self.targetpic.setText("")
        self.targetpic.setObjectName("targetpic")
        self.tarperson = QtWidgets.QPushButton(self.ReID)
        self.tarperson.setGeometry(QtCore.QRect(1250, 269, 304, 281))
        self.tarperson.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tarperson.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.tarperson.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../images/target_person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tarperson.setIcon(icon11)
        self.tarperson.setIconSize(QtCore.QSize(300, 300))
        self.tarperson.setObjectName("tarperson")
        self.reID_res = QtWidgets.QLabel(self.ReID)
        self.reID_res.setGeometry(QtCore.QRect(477, 110, 266, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.reID_res.setFont(font)
        self.reID_res.setObjectName("reID_res")
        self.videos = QtWidgets.QPushButton(self.ReID)
        self.videos.setGeometry(QtCore.QRect(460, 380, 304, 300))
        self.videos.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.videos.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../images/videos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.videos.setIcon(icon12)
        self.videos.setIconSize(QtCore.QSize(250, 250))
        self.videos.setObjectName("videos")
        self.tarperson_btn = QtWidgets.QPushButton(self.ReID)
        self.tarperson_btn.setGeometry(QtCore.QRect(1323, 620, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tarperson_btn.setFont(font)
        self.tarperson_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tarperson_btn.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;}\n"
"")
        self.tarperson_btn.setIconSize(QtCore.QSize(80, 80))
        self.tarperson_btn.setObjectName("tarperson_btn")
        self.reID_revdo = QtWidgets.QPushButton(self.ReID)
        self.reID_revdo.setGeometry(QtCore.QRect(530, 750, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reID_revdo.setFont(font)
        self.reID_revdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reID_revdo.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reID_revdo.setIconSize(QtCore.QSize(80, 80))
        self.reID_revdo.setObjectName("reID_revdo")
        self.label_19 = QtWidgets.QLabel(self.ReID)
        self.label_19.setGeometry(QtCore.QRect(510, 240, 175, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_17 = QtWidgets.QLabel(self.ReID)
        self.label_17.setGeometry(QtCore.QRect(670, 680, 72, 15))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.pics_num = QtWidgets.QLabel(self.ReID)
        self.pics_num.setGeometry(QtCore.QRect(680, 240, 75, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pics_num.setFont(font)
        self.pics_num.setObjectName("pics_num")
        self.label_20 = QtWidgets.QLabel(self.ReID)
        self.label_20.setGeometry(QtCore.QRect(1260, 87, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.ReID)
        self.label_21.setGeometry(QtCore.QRect(1450, 87, 30, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.hitnum = QtWidgets.QLineEdit(self.ReID)
        self.hitnum.setGeometry(QtCore.QRect(1414, 90, 30, 28))
        font = QtGui.QFont()
        font.setFamily("Microdoft YaHei UI")
        font.setPointSize(13)
        self.hitnum.setFont(font)
        self.hitnum.setStyleSheet("QLineEdit{\n"
"    font-family: Microdoft YaHei UI;\n"
"}")
        self.hitnum.setObjectName("hitnum")
        self.sort_cmp = QtWidgets.QLabel(self.ReID)
        self.sort_cmp.setGeometry(QtCore.QRect(450, 110, 337, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.sort_cmp.setFont(font)
        self.sort_cmp.setObjectName("sort_cmp")
        self.reIDbtn = QtWidgets.QPushButton(self.ReID)
        self.reIDbtn.setGeometry(QtCore.QRect(530, 750, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reIDbtn.setFont(font)
        self.reIDbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reIDbtn.setStyleSheet("QPushButton{background-color:#FE3C46;\n"
"                    border:2px solid #FFF;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:2px solid #FE3C46;\n"
"                    color:white;\n"
"                    font-size:26px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:15px;\n"
"                    height:17px;\n"
"                    font-size:25px;\n"
"                    color:white;}\n"
"")
        self.reIDbtn.setIconSize(QtCore.QSize(80, 80))
        self.reIDbtn.setObjectName("reIDbtn")
        self.reslist.raise_()
        self.label_19.raise_()
        self.vdolist.raise_()
        self.reID_vdo.raise_()
        self.reID_reperson.raise_()
        self.reID_submit.raise_()
        self.targetpic.raise_()
        self.tarperson.raise_()
        self.videos.raise_()
        self.tarperson_btn.raise_()
        self.reID_revdo.raise_()
        self.label_17.raise_()
        self.pics_num.raise_()
        self.label_20.raise_()
        self.reID_progressBar.raise_()
        self.label_21.raise_()
        self.hitnum.raise_()
        self.sort_cmp.raise_()
        self.reID_res.raise_()
        self.reIDbtn.raise_()
        self.tabWidget.addTab(self.ReID, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.textBrowser = QtWidgets.QTextBrowser(self.about)
        self.textBrowser.setGeometry(QtCore.QRect(377, 30, 1141, 741))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    border:none;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.label_18 = QtWidgets.QLabel(self.about)
        self.label_18.setGeometry(QtCore.QRect(100, 30, 161, 151))
        self.label_18.setStyleSheet("QLabel{\n"
"    background-color: #bfa\n"
"}")
        self.label_18.setObjectName("label_18")
        self.pushButton_10 = QtWidgets.QPushButton(self.about)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 200, 61, 581))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.pushButton_10.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:/Users/33288/Pictures/Saved Pictures/X-Trace4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon13)
        self.pushButton_10.setIconSize(QtCore.QSize(600, 600))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.about, "")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1471, 20, 111, 68))
        self.label_15.setStyleSheet("QLabel{\n"
"background-color:#FFAA50\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_15.raise_()
        self.tabWidget.raise_()
        TOTAL.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TOTAL)
        self.statusbar.setObjectName("statusbar")
        TOTAL.setStatusBar(self.statusbar)

        self.retranslateUi(TOTAL)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TOTAL)
        TOTAL.setTabOrder(self.tabWidget, self.pushButton)
        TOTAL.setTabOrder(self.pushButton, self.pushButton_2)
        TOTAL.setTabOrder(self.pushButton_2, self.pushButton_6)
        TOTAL.setTabOrder(self.pushButton_6, self.pushButton_3)
        TOTAL.setTabOrder(self.pushButton_3, self.pushButton_4)
        TOTAL.setTabOrder(self.pushButton_4, self.pic_module)
        TOTAL.setTabOrder(self.pic_module, self.reselect_img)
        TOTAL.setTabOrder(self.reselect_img, self.picture_8)
        TOTAL.setTabOrder(self.picture_8, self.picture_9)
        TOTAL.setTabOrder(self.picture_9, self.Slider)
        TOTAL.setTabOrder(self.Slider, self.picture_10)
        TOTAL.setTabOrder(self.picture_10, self.submit_img)
        TOTAL.setTabOrder(self.submit_img, self.picture)
        TOTAL.setTabOrder(self.picture, self.img_list)
        TOTAL.setTabOrder(self.img_list, self.allchecked)
        TOTAL.setTabOrder(self.allchecked, self.allunchecked)
        TOTAL.setTabOrder(self.allunchecked, self.pushButton_9)
        TOTAL.setTabOrder(self.pushButton_9, self.picture_11)
        TOTAL.setTabOrder(self.picture_11, self.picture_12)
        TOTAL.setTabOrder(self.picture_12, self.submit_vdo)
        TOTAL.setTabOrder(self.submit_vdo, self.pushButton_11)
        TOTAL.setTabOrder(self.pushButton_11, self.picture_13)
        TOTAL.setTabOrder(self.picture_13, self.pushButton_15)
        TOTAL.setTabOrder(self.pushButton_15, self.pushButton_16)
        TOTAL.setTabOrder(self.pushButton_16, self.vdo_module)
        TOTAL.setTabOrder(self.vdo_module, self.reselect_vdo)
        TOTAL.setTabOrder(self.reselect_vdo, self.video)
        TOTAL.setTabOrder(self.video, self.Slider_2)
        TOTAL.setTabOrder(self.Slider_2, self.picture_14)
        TOTAL.setTabOrder(self.picture_14, self.allchecked_2)
        TOTAL.setTabOrder(self.allchecked_2, self.pic_2)
        TOTAL.setTabOrder(self.pic_2, self.picture_15)
        TOTAL.setTabOrder(self.picture_15, self.picture_16)
        TOTAL.setTabOrder(self.picture_16, self.save_2)
        TOTAL.setTabOrder(self.save_2, self.pushButton_5)
        TOTAL.setTabOrder(self.pushButton_5, self.save)
        TOTAL.setTabOrder(self.save, self.Slider_3)
        TOTAL.setTabOrder(self.Slider_3, self.camera)
        TOTAL.setTabOrder(self.camera, self.pushButton_7)
        TOTAL.setTabOrder(self.pushButton_7, self.pushButton_8)
        TOTAL.setTabOrder(self.pushButton_8, self.picture_35)
        TOTAL.setTabOrder(self.picture_35, self.picture_36)
        TOTAL.setTabOrder(self.picture_36, self.picture_37)
        TOTAL.setTabOrder(self.picture_37, self.camera_off)

    def retranslateUi(self, TOTAL):
        _translate = QtCore.QCoreApplication.translate
        TOTAL.setWindowTitle(_translate("TOTAL", "X-Trace行人追踪系统"))
        self.save.setText(_translate("TOTAL", "保存"))
        self.label_2.setText(_translate("TOTAL", "识别结果"))
        self.reselect_img.setText(_translate("TOTAL", "重新选择"))
        self.count_img.setText(_translate("TOTAL", "行人数量"))
        self.confidence_coefficient_img.setText(_translate("TOTAL", "置信度"))
        self.threshold_img.setText(_translate("TOTAL", "阈值调控"))
        self.label.setText(_translate("TOTAL", "0"))
        self.label_6.setText(_translate("TOTAL", "1"))
        self.submit_img.setText(_translate("TOTAL", "开始识别"))
        self.picture.setText(_translate("TOTAL", "选择图片"))
        self.label_8.setText(_translate("TOTAL", "图片列表"))
        self.allchecked.setText(_translate("TOTAL", "全选"))
        self.allunchecked.setText(_translate("TOTAL", "全不选"))
        self.waiting.setText(_translate("TOTAL", "正在识别图片, 请稍后..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pic_module), _translate("TOTAL", "图片行人检测"))
        self.confidence_coefficient_vdo.setText(_translate("TOTAL", "置信度"))
        self.submit_vdo.setText(_translate("TOTAL", "开始识别"))
        self.threshold_vdo.setText(_translate("TOTAL", "阈值调控"))
        self.reselect_vdo.setText(_translate("TOTAL", "重新选择"))
        self.video.setText(_translate("TOTAL", "选择视频"))
        self.label_3.setText(_translate("TOTAL", "0"))
        self.label_7.setText(_translate("TOTAL", "1"))
        self.label_5.setText(_translate("TOTAL", "识别结果"))
        self.threshold_vdo_2.setText(_translate("TOTAL", "行人坐标"))
        self.threshold_vdo_3.setText(_translate("TOTAL", "xmax:"))
        self.threshold_vdo_4.setText(_translate("TOTAL", "ymin:"))
        self.threshold_vdo_5.setText(_translate("TOTAL", "ymax:"))
        self.threshold_vdo_6.setText(_translate("TOTAL", "xmin:"))
        self.id.setText(_translate("TOTAL", "行人id："))
        self.xmax.setText(_translate("TOTAL", "0"))
        self.xmin.setText(_translate("TOTAL", "0"))
        self.ymin.setText(_translate("TOTAL", "0"))
        self.ymax.setText(_translate("TOTAL", "0"))
        self.person_counting.setText(_translate("TOTAL", "行人流量曲线"))
        self.ROI_btn.setText(_translate("TOTAL", "ROI区域计数"))
        self.viewcount_vdo_total.setText(_translate("TOTAL", "行人总数"))
        self.viewcount_vdo_ROI.setText(_translate("TOTAL", "ROI区域:"))
        self.count_vdo.setText(_translate("TOTAL", "行人数量"))
        self.count_vdo_total.setText(_translate("TOTAL", "0"))
        self.count_vdo_ROI.setText(_translate("TOTAL", "0"))
        self.label_12.setText(_translate("TOTAL", ":"))
        self.label_16.setText(_translate("TOTAL", "视频进度"))
        self.history.setText(_translate("TOTAL", "历史记录查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vdo_module), _translate("TOTAL", "视频行人追踪"))
        self.allchecked_2.setText(_translate("TOTAL", "全选"))
        self.save_2.setText(_translate("TOTAL", "保存"))
        self.label_10.setText(_translate("TOTAL", "1"))
        self.count_cam.setText(_translate("TOTAL", "人数"))
        self.confidence_coefficient_cam.setText(_translate("TOTAL", "置信度"))
        self.threshold_cam.setText(_translate("TOTAL", "阈值调控"))
        self.label_13.setText(_translate("TOTAL", "0"))
        self.label_14.setText(_translate("TOTAL", "识别结果"))
        self.camera.setText(_translate("TOTAL", "打开摄像头"))
        self.label_40.setText(_translate("TOTAL", "1"))
        self.camera_off.setText(_translate("TOTAL", "关闭摄像头"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cam_module), _translate("TOTAL", "摄像头实时追踪"))
        self.reID_vdo.setText(_translate("TOTAL", "上传视频"))
        self.reID_reperson.setText(_translate("TOTAL", "重选目标"))
        self.reID_submit.setText(_translate("TOTAL", "开始寻找"))
        self.reID_res.setText(_translate("TOTAL", "命中图片显示区"))
        self.tarperson_btn.setText(_translate("TOTAL", "上传目标图片"))
        self.reID_revdo.setText(_translate("TOTAL", "重选视频"))
        self.label_19.setText(_translate("TOTAL", "底库图片数量："))
        self.pics_num.setText(_translate("TOTAL", "0"))
        self.label_20.setText(_translate("TOTAL", "命中图片显示"))
        self.label_21.setText(_translate("TOTAL", "张"))
        self.hitnum.setText(_translate("TOTAL", "20"))
        self.sort_cmp.setText(_translate("TOTAL", "正在排序并比对中..."))
        self.reIDbtn.setText(_translate("TOTAL", "重新寻找"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ReID), _translate("TOTAL", "跨镜头行人追踪"))
        self.textBrowser.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:5px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:135%;\"><span style=\" font-family:\'Microsoft YaHei UI\',\'sans-serif\';\">       “‘X-Trace’行人跟踪系统”将行人检测技术与时下热门的行人跟踪技术相结合，检测与Re-ID整体表现出色。本软件架构完整、UI界面美观、功能全面、交互友好，可广泛应用于智能视频监控、智能安保等领域。</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:135%;\"><span style=\" font-family:\'Microsoft YaHei UI\',\'sans-serif\';\">       GUI窗口采用Qt Designer设计，并且采用PyQt框架实现功能处理和任务调度；采用PyQt的多线程QThread类实现界面的实时更新；前后端的连接则加入了yield生成器，实现前后端的同步以及数据的IO。</span></p></body></html>"))
        self.label_18.setText(_translate("TOTAL", "ICON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("TOTAL", "关于软件"))
