# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TOTAL(object):
    def setupUi(self, TOTAL):
        TOTAL.setObjectName("TOTAL")
        TOTAL.setWindowModality(QtCore.Qt.NonModal)
        TOTAL.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TOTAL.sizePolicy().hasHeightForWidth())
        TOTAL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        TOTAL.setFont(font)
        TOTAL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(TOTAL)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(15, 1, 1570, 875))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("QTabBar::tab{\n"
"background:transparent;color:white;\n"
"padding: 7px 80px;\n"
"margin-left: 50px;\n"
"margin-top: 18px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"background:rgb(255,255,255,100);\n"
"}\n"
"QTabBar::tab:selected{\n"
"border-color:white;background:white;color:#3FC2FF;\n"
"}\n"
"QTabBar{\n"
"background-image:url(\"C:/Users/33288/Pictures/Saved Pictures/topbar3 (2).png\");\n"
"margin-left: -25px;\n"
"}\n"
"QTabWidget::pane{\n"
"border: 5px solid #9794C5;\n"
"}\n"
"\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pic_module = QtWidgets.QWidget()
        self.pic_module.setObjectName("pic_module")
        self.pic = QtWidgets.QPushButton(self.pic_module)
        self.pic.setGeometry(QtCore.QRect(461, 226, 281, 271))
        self.pic.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pic.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.pic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/picture_tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic.setIcon(icon)
        self.pic.setIconSize(QtCore.QSize(400, 400))
        self.pic.setObjectName("pic")
        self.save = QtWidgets.QPushButton(self.pic_module)
        self.save.setGeometry(QtCore.QRect(1425, 764, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:19px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:18px;\n"
"                    color:white;\n"
"}\n"
"")
        self.save.setIconSize(QtCore.QSize(80, 80))
        self.save.setObjectName("save")
        self.pushButton = QtWidgets.QPushButton(self.pic_module)
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../images/rightangle_tl(2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../images/rightangle_bl(2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_3.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../images/rightangle_tr(2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.pic_module)
        self.pushButton_4.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../images/rightangle_br(2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.pic_module)
        self.label_2.setGeometry(QtCore.QRect(1333, 32, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_12 = QtWidgets.QFrame(self.pic_module)
        self.line_12.setGeometry(QtCore.QRect(1281, 74, 252, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.reselect_img = QtWidgets.QPushButton(self.pic_module)
        self.reselect_img.setGeometry(QtCore.QRect(850, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reselect_img.setFont(font)
        self.reselect_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reselect_img.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.reselect_img.setIconSize(QtCore.QSize(80, 80))
        self.reselect_img.setObjectName("reselect_img")
        self.picture_8 = QtWidgets.QPushButton(self.pic_module)
        self.picture_8.setGeometry(QtCore.QRect(1290, 98, 69, 65))
        self.picture_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_8.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../images/count.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_8.setIcon(icon5)
        self.picture_8.setIconSize(QtCore.QSize(55, 55))
        self.picture_8.setObjectName("picture_8")
        self.count_img = QtWidgets.QLabel(self.pic_module)
        self.count_img.setGeometry(QtCore.QRect(1364, 115, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_img.setFont(font)
        self.count_img.setObjectName("count_img")
        self.picture_9 = QtWidgets.QPushButton(self.pic_module)
        self.picture_9.setGeometry(QtCore.QRect(1298, 197, 54, 50))
        self.picture_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_9.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_9.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../images/confidence_coefficient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_9.setIcon(icon6)
        self.picture_9.setIconSize(QtCore.QSize(50, 50))
        self.picture_9.setObjectName("picture_9")
        self.confidence_coefficient_img = QtWidgets.QLabel(self.pic_module)
        self.confidence_coefficient_img.setGeometry(QtCore.QRect(1370, 205, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_img.setFont(font)
        self.confidence_coefficient_img.setObjectName("confidence_coefficient_img")
        self.Slider = QtWidgets.QSlider(self.pic_module)
        self.Slider.setGeometry(QtCore.QRect(1303, 355, 211, 22))
        self.Slider.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider.setMinimum(1)
        self.Slider.setMaximum(100)
        self.Slider.setSingleStep(1)
        self.Slider.setPageStep(1)
        self.Slider.setProperty("value", 50)
        self.Slider.setSliderPosition(50)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.threshold_img = QtWidgets.QLabel(self.pic_module)
        self.threshold_img.setGeometry(QtCore.QRect(1364, 295, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_img.setFont(font)
        self.threshold_img.setObjectName("threshold_img")
        self.picture_10 = QtWidgets.QPushButton(self.pic_module)
        self.picture_10.setGeometry(QtCore.QRect(1300, 285, 54, 50))
        self.picture_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_10.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_10.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../images/threshold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_10.setIcon(icon7)
        self.picture_10.setIconSize(QtCore.QSize(53, 53))
        self.picture_10.setObjectName("picture_10")
        self.represent_img = QtWidgets.QLabel(self.pic_module)
        self.represent_img.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_img.setStyleSheet("QLabel{\n"
"background-color:\n"
"}")
        self.represent_img.setText("")
        self.represent_img.setObjectName("represent_img")
        self.label = QtWidgets.QLabel(self.pic_module)
        self.label.setGeometry(QtCore.QRect(1304, 374, 8, 15))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.pic_module)
        self.label_6.setGeometry(QtCore.QRect(1510, 374, 8, 15))
        self.label_6.setObjectName("label_6")
        self.submit_img = QtWidgets.QPushButton(self.pic_module)
        self.submit_img.setGeometry(QtCore.QRect(230, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submit_img.setFont(font)
        self.submit_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_img.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.submit_img.setIconSize(QtCore.QSize(80, 80))
        self.submit_img.setObjectName("submit_img")
        self.picture = QtWidgets.QPushButton(self.pic_module)
        self.picture.setGeometry(QtCore.QRect(530, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.picture.setFont(font)
        self.picture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.picture.setIconSize(QtCore.QSize(80, 80))
        self.picture.setObjectName("picture")
        self.img_list = QtWidgets.QListWidget(self.pic_module)
        self.img_list.setGeometry(QtCore.QRect(1289, 491, 238, 261))
        self.img_list.setObjectName("img_list")
        self.line_14 = QtWidgets.QFrame(self.pic_module)
        self.line_14.setGeometry(QtCore.QRect(1282, 413, 252, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_8 = QtWidgets.QLabel(self.pic_module)
        self.label_8.setGeometry(QtCore.QRect(1333, 440, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.pic_module)
        self.label_9.setGeometry(QtCore.QRect(1281, 44, 251, 811))
        self.label_9.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.allchecked = QtWidgets.QPushButton(self.pic_module)
        self.allchecked.setGeometry(QtCore.QRect(1289, 764, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allchecked.setFont(font)
        self.allchecked.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allchecked.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:19px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:18px;\n"
"                    color:white;\n"
"}\n"
"")
        self.allchecked.setIconSize(QtCore.QSize(80, 80))
        self.allchecked.setObjectName("allchecked")
        self.allunchecked = QtWidgets.QPushButton(self.pic_module)
        self.allunchecked.setGeometry(QtCore.QRect(1289, 764, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allunchecked.setFont(font)
        self.allunchecked.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allunchecked.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:19px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:18px;\n"
"                    color:white;\n"
"}\n"
"")
        self.allunchecked.setIconSize(QtCore.QSize(80, 80))
        self.allunchecked.setObjectName("allunchecked")
        self.waiting = QtWidgets.QLabel(self.pic_module)
        self.waiting.setGeometry(QtCore.QRect(401, 336, 451, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.waiting.setFont(font)
        self.waiting.setObjectName("waiting")
        self.waiting.raise_()
        self.pic.raise_()
        self.label_9.raise_()
        self.save.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_2.raise_()
        self.line_12.raise_()
        self.reselect_img.raise_()
        self.picture_8.raise_()
        self.count_img.raise_()
        self.picture_9.raise_()
        self.confidence_coefficient_img.raise_()
        self.Slider.raise_()
        self.threshold_img.raise_()
        self.picture_10.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.submit_img.raise_()
        self.picture.raise_()
        self.img_list.raise_()
        self.line_14.raise_()
        self.label_8.raise_()
        self.allchecked.raise_()
        self.allunchecked.raise_()
        self.represent_img.raise_()
        self.tabWidget.addTab(self.pic_module, "")
        self.vdo_module = QtWidgets.QWidget()
        self.vdo_module.setObjectName("vdo_module")
        self.confidence_coefficient_vdo = QtWidgets.QLabel(self.vdo_module)
        self.confidence_coefficient_vdo.setGeometry(QtCore.QRect(1370, 205, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_vdo.setFont(font)
        self.confidence_coefficient_vdo.setObjectName("confidence_coefficient_vdo")
        self.pushButton_9 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.picture_11 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_11.setGeometry(QtCore.QRect(1290, 98, 69, 65))
        self.picture_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_11.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_11.setText("")
        self.picture_11.setIcon(icon5)
        self.picture_11.setIconSize(QtCore.QSize(55, 55))
        self.picture_11.setObjectName("picture_11")
        self.picture_12 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_12.setGeometry(QtCore.QRect(1300, 285, 54, 50))
        self.picture_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_12.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_12.setText("")
        self.picture_12.setIcon(icon7)
        self.picture_12.setIconSize(QtCore.QSize(53, 53))
        self.picture_12.setObjectName("picture_12")
        self.label_4 = QtWidgets.QLabel(self.vdo_module)
        self.label_4.setGeometry(QtCore.QRect(1281, 15, 253, 811))
        self.label_4.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.submit_vdo = QtWidgets.QPushButton(self.vdo_module)
        self.submit_vdo.setGeometry(QtCore.QRect(220, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submit_vdo.setFont(font)
        self.submit_vdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_vdo.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.submit_vdo.setIconSize(QtCore.QSize(80, 80))
        self.submit_vdo.setObjectName("submit_vdo")
        self.line_13 = QtWidgets.QFrame(self.vdo_module)
        self.line_13.setGeometry(QtCore.QRect(1281, 74, 252, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_11.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.picture_13 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_13.setGeometry(QtCore.QRect(1298, 197, 54, 50))
        self.picture_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_13.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_13.setText("")
        self.picture_13.setIcon(icon6)
        self.picture_13.setIconSize(QtCore.QSize(50, 50))
        self.picture_13.setObjectName("picture_13")
        self.threshold_vdo = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo.setGeometry(QtCore.QRect(1364, 295, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_vdo.setFont(font)
        self.threshold_vdo.setObjectName("threshold_vdo")
        self.pushButton_15 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_15.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon3)
        self.pushButton_15.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.vdo_module)
        self.pushButton_16.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon2)
        self.pushButton_16.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.vdo = QtWidgets.QPushButton(self.vdo_module)
        self.vdo.setGeometry(QtCore.QRect(450, 214, 304, 300))
        self.vdo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.vdo.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.vdo.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../images/video_tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vdo.setIcon(icon8)
        self.vdo.setIconSize(QtCore.QSize(300, 300))
        self.vdo.setObjectName("vdo")
        self.represent_vdo = QtWidgets.QLabel(self.vdo_module)
        self.represent_vdo.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_vdo.setStyleSheet("QLabel{\n"
"background-color: \n"
"}")
        self.represent_vdo.setText("")
        self.represent_vdo.setObjectName("represent_vdo")
        self.reselect_vdo = QtWidgets.QPushButton(self.vdo_module)
        self.reselect_vdo.setGeometry(QtCore.QRect(950, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.reselect_vdo.setFont(font)
        self.reselect_vdo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reselect_vdo.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.reselect_vdo.setIconSize(QtCore.QSize(80, 80))
        self.reselect_vdo.setObjectName("reselect_vdo")
        self.video = QtWidgets.QPushButton(self.vdo_module)
        self.video.setGeometry(QtCore.QRect(530, 720, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.video.setFont(font)
        self.video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.video.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.video.setIconSize(QtCore.QSize(80, 80))
        self.video.setObjectName("video")
        self.Slider_2 = QtWidgets.QSlider(self.vdo_module)
        self.Slider_2.setGeometry(QtCore.QRect(1303, 355, 211, 22))
        self.Slider_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider_2.setMinimum(1)
        self.Slider_2.setMaximum(100)
        self.Slider_2.setSingleStep(1)
        self.Slider_2.setPageStep(1)
        self.Slider_2.setProperty("value", 90)
        self.Slider_2.setSliderPosition(90)
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setObjectName("Slider_2")
        self.label_3 = QtWidgets.QLabel(self.vdo_module)
        self.label_3.setGeometry(QtCore.QRect(1304, 374, 8, 15))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.vdo_module)
        self.label_7.setGeometry(QtCore.QRect(1510, 374, 8, 15))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.vdo_module)
        self.label_5.setGeometry(QtCore.QRect(1333, 32, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.picture_17 = QtWidgets.QPushButton(self.vdo_module)
        self.picture_17.setGeometry(QtCore.QRect(1300, 504, 54, 50))
        self.picture_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_17.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_17.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../images/pisition.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture_17.setIcon(icon9)
        self.picture_17.setIconSize(QtCore.QSize(50, 50))
        self.picture_17.setObjectName("picture_17")
        self.threshold_vdo_2 = QtWidgets.QLabel(self.vdo_module)
        self.threshold_vdo_2.setGeometry(QtCore.QRect(1364, 514, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_vdo_2.setFont(font)
        self.threshold_vdo_2.setObjectName("threshold_vdo_2")
        self.line_17 = QtWidgets.QFrame(self.vdo_module)
        self.line_17.setGeometry(QtCore.QRect(1282, 413, 252, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.idBox = QtWidgets.QComboBox(self.vdo_module)
        self.idBox.setGeometry(QtCore.QRect(1412, 455, 111, 26))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idBox.setFont(font)
        self.idBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.idBox.setStyleSheet("QComboBox{\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #000;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    border-image: url(E:/python/Competition/PYQT/images/drop.png)\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: none;\n"
"}")
        self.idBox.setObjectName("idBox")
        self.idBox.addItem("")
        self.xmax = QtWidgets.QLabel(self.vdo_module)
        self.xmax.setGeometry(QtCore.QRect(1295, 583, 59, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.xmax.setFont(font)
        self.xmax.setObjectName("xmax")
        self.ymin = QtWidgets.QLabel(self.vdo_module)
        self.ymin.setGeometry(QtCore.QRect(1419, 644, 53, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ymin.setFont(font)
        self.ymin.setObjectName("ymin")
        self.ymax = QtWidgets.QLabel(self.vdo_module)
        self.ymax.setGeometry(QtCore.QRect(1295, 644, 59, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ymax.setFont(font)
        self.ymax.setObjectName("ymax")
        self.xmin = QtWidgets.QLabel(self.vdo_module)
        self.xmin.setGeometry(QtCore.QRect(1419, 583, 53, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.xmin.setFont(font)
        self.xmin.setObjectName("xmin")
        self.id = QtWidgets.QLabel(self.vdo_module)
        self.id.setGeometry(QtCore.QRect(1290, 449, 136, 33))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.xma = QtWidgets.QLabel(self.vdo_module)
        self.xma.setGeometry(QtCore.QRect(1355, 583, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.xma.setFont(font)
        self.xma.setObjectName("xma")
        self.xmi = QtWidgets.QLabel(self.vdo_module)
        self.xmi.setGeometry(QtCore.QRect(1472, 583, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.xmi.setFont(font)
        self.xmi.setObjectName("xmi")
        self.yma = QtWidgets.QLabel(self.vdo_module)
        self.yma.setGeometry(QtCore.QRect(1355, 644, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.yma.setFont(font)
        self.yma.setObjectName("yma")
        self.ymi = QtWidgets.QLabel(self.vdo_module)
        self.ymi.setGeometry(QtCore.QRect(1472, 644, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ymi.setFont(font)
        self.ymi.setObjectName("ymi")
        self.line_18 = QtWidgets.QFrame(self.vdo_module)
        self.line_18.setGeometry(QtCore.QRect(1281, 684, 252, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.person_counting = QtWidgets.QPushButton(self.vdo_module)
        self.person_counting.setGeometry(QtCore.QRect(1330, 730, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.person_counting.setFont(font)
        self.person_counting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.person_counting.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.person_counting.setIconSize(QtCore.QSize(80, 80))
        self.person_counting.setObjectName("person_counting")
        self.ROI = QtWidgets.QPushButton(self.vdo_module)
        self.ROI.setGeometry(QtCore.QRect(1330, 730, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ROI.setFont(font)
        self.ROI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ROI.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.ROI.setIconSize(QtCore.QSize(80, 80))
        self.ROI.setObjectName("ROI")
        self.viewcount_vdo_total = QtWidgets.QLabel(self.vdo_module)
        self.viewcount_vdo_total.setGeometry(QtCore.QRect(1360, 106, 112, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.viewcount_vdo_total.setFont(font)
        self.viewcount_vdo_total.setObjectName("viewcount_vdo_total")
        self.viewcount_vdo_ROI = QtWidgets.QLabel(self.vdo_module)
        self.viewcount_vdo_ROI.setGeometry(QtCore.QRect(1365, 144, 112, 27))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.viewcount_vdo_ROI.setFont(font)
        self.viewcount_vdo_ROI.setObjectName("viewcount_vdo_ROI")
        self.count_vdo = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo.setGeometry(QtCore.QRect(1364, 115, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_vdo.setFont(font)
        self.count_vdo.setObjectName("count_vdo")
        self.count_vdo_total = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo_total.setGeometry(QtCore.QRect(1479, 109, 48, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_vdo_total.setFont(font)
        self.count_vdo_total.setObjectName("count_vdo_total")
        self.count_vdo_ROI = QtWidgets.QLabel(self.vdo_module)
        self.count_vdo_ROI.setGeometry(QtCore.QRect(1478, 146, 48, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_vdo_ROI.setFont(font)
        self.count_vdo_ROI.setObjectName("count_vdo_ROI")
        self.label_12 = QtWidgets.QLabel(self.vdo_module)
        self.label_12.setGeometry(QtCore.QRect(1468, 105, 14, 28))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(17)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progressBar = QtWidgets.QProgressBar(self.vdo_module)
        self.progressBar.setGeometry(QtCore.QRect(130, 720, 821, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.raise_()
        self.vdo.raise_()
        self.represent_vdo.raise_()
        self.label_4.raise_()
        self.confidence_coefficient_vdo.raise_()
        self.pushButton_9.raise_()
        self.picture_11.raise_()
        self.picture_12.raise_()
        self.submit_vdo.raise_()
        self.line_13.raise_()
        self.pushButton_11.raise_()
        self.picture_13.raise_()
        self.threshold_vdo.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.reselect_vdo.raise_()
        self.video.raise_()
        self.Slider_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.picture_17.raise_()
        self.threshold_vdo_2.raise_()
        self.line_17.raise_()
        self.idBox.raise_()
        self.xmax.raise_()
        self.ymin.raise_()
        self.ymax.raise_()
        self.xmin.raise_()
        self.id.raise_()
        self.xma.raise_()
        self.xmi.raise_()
        self.yma.raise_()
        self.ymi.raise_()
        self.line_18.raise_()
        self.person_counting.raise_()
        self.ROI.raise_()
        self.viewcount_vdo_total.raise_()
        self.viewcount_vdo_ROI.raise_()
        self.count_vdo_total.raise_()
        self.count_vdo_ROI.raise_()
        self.label_12.raise_()
        self.count_vdo.raise_()
        self.tabWidget.addTab(self.vdo_module, "")
        self.cam_module = QtWidgets.QWidget()
        self.cam_module.setObjectName("cam_module")
        self.line_15 = QtWidgets.QFrame(self.cam_module)
        self.line_15.setGeometry(QtCore.QRect(1281, 74, 252, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.picture_14 = QtWidgets.QPushButton(self.cam_module)
        self.picture_14.setGeometry(QtCore.QRect(1290, 98, 69, 65))
        self.picture_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_14.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_14.setText("")
        self.picture_14.setIcon(icon5)
        self.picture_14.setIconSize(QtCore.QSize(55, 55))
        self.picture_14.setObjectName("picture_14")
        self.allchecked_2 = QtWidgets.QPushButton(self.cam_module)
        self.allchecked_2.setGeometry(QtCore.QRect(1289, 764, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allchecked_2.setFont(font)
        self.allchecked_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allchecked_2.setStyleSheet("QPushButton{background-color:rgb(254,0,0);\n"
"                    border:2px solid #fe0000;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:18px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:17px;\n"
"                    color:white;}\n"
"")
        self.allchecked_2.setIconSize(QtCore.QSize(80, 80))
        self.allchecked_2.setObjectName("allchecked_2")
        self.pic_2 = QtWidgets.QPushButton(self.cam_module)
        self.pic_2.setGeometry(QtCore.QRect(462, 230, 279, 275))
        self.pic_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pic_2.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.pic_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../images/camera_tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic_2.setIcon(icon10)
        self.pic_2.setIconSize(QtCore.QSize(275, 275))
        self.pic_2.setObjectName("pic_2")
        self.picture_15 = QtWidgets.QPushButton(self.cam_module)
        self.picture_15.setGeometry(QtCore.QRect(1300, 285, 54, 50))
        self.picture_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_15.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_15.setText("")
        self.picture_15.setIcon(icon7)
        self.picture_15.setIconSize(QtCore.QSize(53, 53))
        self.picture_15.setObjectName("picture_15")
        self.picture_16 = QtWidgets.QPushButton(self.cam_module)
        self.picture_16.setGeometry(QtCore.QRect(1298, 197, 54, 50))
        self.picture_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_16.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_16.setText("")
        self.picture_16.setIcon(icon6)
        self.picture_16.setIconSize(QtCore.QSize(50, 50))
        self.picture_16.setObjectName("picture_16")
        self.save_2 = QtWidgets.QPushButton(self.cam_module)
        self.save_2.setGeometry(QtCore.QRect(1425, 764, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_2.setFont(font)
        self.save_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_2.setStyleSheet("QPushButton{background-color:rgb(254,0,0);\n"
"                    border:2px solid #fe0000;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:18px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #fff;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:17px;\n"
"                    color:white;}\n"
"")
        self.save_2.setIconSize(QtCore.QSize(80, 80))
        self.save_2.setObjectName("save_2")
        self.label_10 = QtWidgets.QLabel(self.cam_module)
        self.label_10.setGeometry(QtCore.QRect(1510, 374, 8, 15))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.cam_module)
        self.label_11.setGeometry(QtCore.QRect(1281, 14, 253, 811))
        self.label_11.setStyleSheet("QLabel{\n"
"background-color: #f0f0f0;\n"
"border-radius: 20px;\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.count_cam = QtWidgets.QLabel(self.cam_module)
        self.count_cam.setGeometry(QtCore.QRect(1364, 115, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.count_cam.setFont(font)
        self.count_cam.setObjectName("count_cam")
        self.confidence_coefficient_cam = QtWidgets.QLabel(self.cam_module)
        self.confidence_coefficient_cam.setGeometry(QtCore.QRect(1370, 205, 114, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.confidence_coefficient_cam.setFont(font)
        self.confidence_coefficient_cam.setObjectName("confidence_coefficient_cam")
        self.pushButton_5 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_5.setGeometry(QtCore.QRect(1098, 642, 54, 50))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 60, 54, 50))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.threshold_cam = QtWidgets.QLabel(self.cam_module)
        self.threshold_cam.setGeometry(QtCore.QRect(1364, 295, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_cam.setFont(font)
        self.threshold_cam.setObjectName("threshold_cam")
        self.label_13 = QtWidgets.QLabel(self.cam_module)
        self.label_13.setGeometry(QtCore.QRect(1304, 374, 8, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.cam_module)
        self.label_14.setGeometry(QtCore.QRect(1333, 32, 152, 37))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Slider_3 = QtWidgets.QSlider(self.cam_module)
        self.Slider_3.setGeometry(QtCore.QRect(1303, 355, 211, 22))
        self.Slider_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.Slider_3.setMinimum(1)
        self.Slider_3.setMaximum(100)
        self.Slider_3.setSingleStep(1)
        self.Slider_3.setPageStep(1)
        self.Slider_3.setProperty("value", 90)
        self.Slider_3.setSliderPosition(90)
        self.Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_3.setObjectName("Slider_3")
        self.represent_cam = QtWidgets.QLabel(self.cam_module)
        self.represent_cam.setGeometry(QtCore.QRect(141, 106, 960, 540))
        self.represent_cam.setStyleSheet("QLabel{\n"
"background-color: \n"
"}")
        self.represent_cam.setText("")
        self.represent_cam.setObjectName("represent_cam")
        self.camera = QtWidgets.QPushButton(self.cam_module)
        self.camera.setGeometry(QtCore.QRect(498, 720, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.camera.setIconSize(QtCore.QSize(80, 80))
        self.camera.setObjectName("camera")
        self.line_16 = QtWidgets.QFrame(self.cam_module)
        self.line_16.setGeometry(QtCore.QRect(1282, 413, 252, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.pushButton_7 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 642, 54, 50))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.cam_module)
        self.pushButton_8.setGeometry(QtCore.QRect(1098, 60, 54, 50))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.picture_35 = QtWidgets.QPushButton(self.cam_module)
        self.picture_35.setGeometry(QtCore.QRect(1300, 285, 54, 50))
        self.picture_35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_35.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_35.setText("")
        self.picture_35.setIcon(icon7)
        self.picture_35.setIconSize(QtCore.QSize(53, 53))
        self.picture_35.setObjectName("picture_35")
        self.picture_36 = QtWidgets.QPushButton(self.cam_module)
        self.picture_36.setGeometry(QtCore.QRect(1298, 197, 54, 50))
        self.picture_36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_36.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_36.setText("")
        self.picture_36.setIcon(icon6)
        self.picture_36.setIconSize(QtCore.QSize(50, 50))
        self.picture_36.setObjectName("picture_36")
        self.picture_37 = QtWidgets.QPushButton(self.cam_module)
        self.picture_37.setGeometry(QtCore.QRect(1290, 98, 69, 65))
        self.picture_37.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.picture_37.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"QBUshButton::hover{\n"
"border: 1px solid white;\n"
"border-radius: 15px;\n"
"}")
        self.picture_37.setText("")
        self.picture_37.setIcon(icon5)
        self.picture_37.setIconSize(QtCore.QSize(55, 55))
        self.picture_37.setObjectName("picture_37")
        self.label_40 = QtWidgets.QLabel(self.cam_module)
        self.label_40.setGeometry(QtCore.QRect(1510, 374, 8, 15))
        self.label_40.setObjectName("label_40")
        self.camera_off = QtWidgets.QPushButton(self.cam_module)
        self.camera_off.setGeometry(QtCore.QRect(498, 720, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Roman time")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.camera_off.setFont(font)
        self.camera_off.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_off.setStyleSheet("QPushButton{background-color:#0167F0;\n"
"                    border:2px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white\n"
"                  }\n"
"                  QPushButton:hover\n"
"                  {\n"
"                    border:1px solid #0167F0;\n"
"                    border-radius:5px;\n"
"                    color:white;\n"
"                    font-size:24px;\n"
"                  }\n"
"                  QPushButton:hover:pressed\n"
"                  {\n"
"                    border:1px solid #60C9F9;\n"
"                    border-radius:17px;\n"
"                    height:17px;\n"
"                    font-size:23px;\n"
"                    color:white;\n"
"}\n"
"")
        self.camera_off.setIconSize(QtCore.QSize(80, 80))
        self.camera_off.setObjectName("camera_off")
        self.represent_cam.raise_()
        self.pic_2.raise_()
        self.camera_off.raise_()
        self.line_15.raise_()
        self.picture_14.raise_()
        self.allchecked_2.raise_()
        self.picture_15.raise_()
        self.picture_16.raise_()
        self.save_2.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.count_cam.raise_()
        self.confidence_coefficient_cam.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.threshold_cam.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.Slider_3.raise_()
        self.camera.raise_()
        self.line_16.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.picture_35.raise_()
        self.picture_36.raise_()
        self.picture_37.raise_()
        self.label_40.raise_()
        self.tabWidget.addTab(self.cam_module, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.tabWidget.addTab(self.about, "")
        TOTAL.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TOTAL)
        self.statusbar.setObjectName("statusbar")
        TOTAL.setStatusBar(self.statusbar)

        self.retranslateUi(TOTAL)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TOTAL)
        TOTAL.setTabOrder(self.tabWidget, self.pushButton)
        TOTAL.setTabOrder(self.pushButton, self.pushButton_2)
        TOTAL.setTabOrder(self.pushButton_2, self.pushButton_6)
        TOTAL.setTabOrder(self.pushButton_6, self.pushButton_3)
        TOTAL.setTabOrder(self.pushButton_3, self.pushButton_4)
        TOTAL.setTabOrder(self.pushButton_4, self.pic_module)
        TOTAL.setTabOrder(self.pic_module, self.reselect_img)
        TOTAL.setTabOrder(self.reselect_img, self.picture_8)
        TOTAL.setTabOrder(self.picture_8, self.picture_9)
        TOTAL.setTabOrder(self.picture_9, self.Slider)
        TOTAL.setTabOrder(self.Slider, self.picture_10)
        TOTAL.setTabOrder(self.picture_10, self.submit_img)
        TOTAL.setTabOrder(self.submit_img, self.picture)
        TOTAL.setTabOrder(self.picture, self.img_list)
        TOTAL.setTabOrder(self.img_list, self.allchecked)
        TOTAL.setTabOrder(self.allchecked, self.allunchecked)
        TOTAL.setTabOrder(self.allunchecked, self.pushButton_9)
        TOTAL.setTabOrder(self.pushButton_9, self.picture_11)
        TOTAL.setTabOrder(self.picture_11, self.picture_12)
        TOTAL.setTabOrder(self.picture_12, self.submit_vdo)
        TOTAL.setTabOrder(self.submit_vdo, self.pushButton_11)
        TOTAL.setTabOrder(self.pushButton_11, self.picture_13)
        TOTAL.setTabOrder(self.picture_13, self.pushButton_15)
        TOTAL.setTabOrder(self.pushButton_15, self.pushButton_16)
        TOTAL.setTabOrder(self.pushButton_16, self.vdo_module)
        TOTAL.setTabOrder(self.vdo_module, self.reselect_vdo)
        TOTAL.setTabOrder(self.reselect_vdo, self.video)
        TOTAL.setTabOrder(self.video, self.Slider_2)
        TOTAL.setTabOrder(self.Slider_2, self.picture_14)
        TOTAL.setTabOrder(self.picture_14, self.allchecked_2)
        TOTAL.setTabOrder(self.allchecked_2, self.pic_2)
        TOTAL.setTabOrder(self.pic_2, self.picture_15)
        TOTAL.setTabOrder(self.picture_15, self.picture_16)
        TOTAL.setTabOrder(self.picture_16, self.save_2)
        TOTAL.setTabOrder(self.save_2, self.pushButton_5)
        TOTAL.setTabOrder(self.pushButton_5, self.save)
        TOTAL.setTabOrder(self.save, self.Slider_3)
        TOTAL.setTabOrder(self.Slider_3, self.camera)
        TOTAL.setTabOrder(self.camera, self.pushButton_7)
        TOTAL.setTabOrder(self.pushButton_7, self.pushButton_8)
        TOTAL.setTabOrder(self.pushButton_8, self.picture_35)
        TOTAL.setTabOrder(self.picture_35, self.picture_36)
        TOTAL.setTabOrder(self.picture_36, self.picture_37)
        TOTAL.setTabOrder(self.picture_37, self.camera_off)

    def retranslateUi(self, TOTAL):
        _translate = QtCore.QCoreApplication.translate
        TOTAL.setWindowTitle(_translate("TOTAL", "X-Trace行人追踪系统"))
        self.save.setText(_translate("TOTAL", "保存"))
        self.label_2.setText(_translate("TOTAL", "识别结果"))
        self.reselect_img.setText(_translate("TOTAL", "重新选择"))
        self.count_img.setText(_translate("TOTAL", "行人数量"))
        self.confidence_coefficient_img.setText(_translate("TOTAL", "置信度"))
        self.threshold_img.setText(_translate("TOTAL", "阈值调控"))
        self.label.setText(_translate("TOTAL", "0"))
        self.label_6.setText(_translate("TOTAL", "1"))
        self.submit_img.setText(_translate("TOTAL", "开始识别"))
        self.picture.setText(_translate("TOTAL", "选择图片"))
        self.label_8.setText(_translate("TOTAL", "图片列表"))
        self.allchecked.setText(_translate("TOTAL", "全选"))
        self.allunchecked.setText(_translate("TOTAL", "全不选"))
        self.waiting.setText(_translate("TOTAL", "正在识别图片, 请稍后..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pic_module), _translate("TOTAL", "图片行人检测"))
        self.confidence_coefficient_vdo.setText(_translate("TOTAL", "置信度"))
        self.submit_vdo.setText(_translate("TOTAL", "开始识别"))
        self.threshold_vdo.setText(_translate("TOTAL", "阈值调控"))
        self.reselect_vdo.setText(_translate("TOTAL", "重新选择"))
        self.video.setText(_translate("TOTAL", "选择视频"))
        self.label_3.setText(_translate("TOTAL", "0"))
        self.label_7.setText(_translate("TOTAL", "1"))
        self.label_5.setText(_translate("TOTAL", "识别结果"))
        self.threshold_vdo_2.setText(_translate("TOTAL", "行人坐标"))
        self.idBox.setItemText(0, _translate("TOTAL", "所有目标"))
        self.xmax.setText(_translate("TOTAL", "xmax:"))
        self.ymin.setText(_translate("TOTAL", "ymin:"))
        self.ymax.setText(_translate("TOTAL", "ymax:"))
        self.xmin.setText(_translate("TOTAL", "xmin:"))
        self.id.setText(_translate("TOTAL", "行人id："))
        self.xma.setText(_translate("TOTAL", "0"))
        self.xmi.setText(_translate("TOTAL", "0"))
        self.yma.setText(_translate("TOTAL", "0"))
        self.ymi.setText(_translate("TOTAL", "0"))
        self.person_counting.setText(_translate("TOTAL", "行人流量曲线"))
        self.ROI.setText(_translate("TOTAL", "ROI区域计数"))
        self.viewcount_vdo_total.setText(_translate("TOTAL", "行人总数"))
        self.viewcount_vdo_ROI.setText(_translate("TOTAL", "ROI区域:"))
        self.count_vdo.setText(_translate("TOTAL", "行人数量"))
        self.count_vdo_total.setText(_translate("TOTAL", "0"))
        self.count_vdo_ROI.setText(_translate("TOTAL", "0"))
        self.label_12.setText(_translate("TOTAL", ":"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vdo_module), _translate("TOTAL", "视频行人追踪"))
        self.allchecked_2.setText(_translate("TOTAL", "全选"))
        self.save_2.setText(_translate("TOTAL", "保存"))
        self.label_10.setText(_translate("TOTAL", "1"))
        self.count_cam.setText(_translate("TOTAL", "人数"))
        self.confidence_coefficient_cam.setText(_translate("TOTAL", "置信度"))
        self.threshold_cam.setText(_translate("TOTAL", "阈值调控"))
        self.label_13.setText(_translate("TOTAL", "0"))
        self.label_14.setText(_translate("TOTAL", "识别结果"))
        self.camera.setText(_translate("TOTAL", "打开摄像头"))
        self.label_40.setText(_translate("TOTAL", "1"))
        self.camera_off.setText(_translate("TOTAL", "关闭摄像头"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cam_module), _translate("TOTAL", "摄像头实时追踪"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("TOTAL", "关于软件"))
